### ISSUE TITLE
the screen capture button is not displayed

### ISSUE THREAD

**Issue by JavierKiconex** [cconard96/glpi-screenshot-plugin#10]
Hi,

I have installed the screenShot plugin and the button to capture the tickets is not shown, I attach images of the configuration

![pluginActive](https://user-images.githubusercontent.com/71820083/100623704-cdd31700-3322-11eb-8cb9-951ad139fa1a.PNG)

![ScreenShotSettings](https://user-images.githubusercontent.com/71820083/100623709-d1669e00-3322-11eb-856a-34670a5fe730.PNG)

![bottonScreenShot](https://user-images.githubusercontent.com/71820083/100623907-12f74900-3323-11eb-82b6-547a673510f7.PNG)

Regards

**Comment by cconard96** [comment]
Are you connected to GLPI over HTTPS or HTTP? Browsers only let this feature over HTTPS or localhost so this plugin hides the button if you wouldn't be able to use it to avoid confusion.

**Comment by JavierKiconex** [comment]
I am connected by https with a certificate self-signed by us by being a test environment, I attach an image

![bottonScreenShot](https://user-images.githubusercontent.com/71820083/100627799-bea29800-3327-11eb-8224-1e52ac5255f7.PNG)

**Comment by cconard96** [comment]
I see the issue now. This plugin doesn't work with Firefox yet because it doesn't support the ImageCapture functionality.
See the following for browser compatibility:
https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture#Browser_compatibility

I have an open issue to try and expand compatibility through 3rd party libraries that add this functionality but I haven't found time to research the available solutions and implement one. I should have something in the next week for this.

In the meantime, anything Chromium based (like Chrome) should work.

**Comment by JavierKiconex** [comment]
Hi,

thanks for the information, if you don't mind when you have the functionality implemented for firefox notify me.

Greetings thanks for your time

**Comment by cconard96** [comment]
@JavierKiconex Can you test the current master branch or 1.1/fixes to see if it works properly for you in Firefox?
The work done in #11 should allow the plugin to work in any modern desktop browser.

**Comment by JavierKiconex** [comment]
thanks, it works perfectly on Firefox Browser version 83 (64bit) windows 10
