### ISSUE TITLE
Form creator plugin integration

### ISSUE THREAD

**Issue by cyrakuse** [cconard96/glpi-screenshot-plugin#27]
We use the Form Creator plugin.
Is it possible to add a new type of question that integrate the screen shot plugin.
With that, we could take a screenshot in a form and join it to a ticket.

**Comment by cconard96** [comment]
Are you asking for the ability to have a form field that asks a user for a screenshot and they can directly add one when they are filling it out? I know there is a built-in file upload field that can be used as a work-around. I'm not sure if there is a way for plugins to add new field types. From a quick look, it looks like they scan for files in their own plugin directory to figure out which field types exist.

There may need to be changes made to both plugins to get an integration to work.

**Comment by cyrakuse** [comment]
That is exactly that.

**Comment by cconard96** [comment]
I know it has been a long time, but I have a *small* update.
This plugin won't be supported past GLPI 10.X, but only because it is going to be a part of GLPI itself starting with GLPI 10.1. Further, the forms feature provided by Form Creator will also be redone as a core feature of GLPI 10.1.

The native forms may or may not support screenshots at release, but the suggestion doesn't make sense anymore at the plugin level.
